In [3]:
# def a function evaluate the fitting goodness of dataset by Gpr model and LOOCV
import math
import warnings
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
from sklearn.model_selection import LeaveOneOut
warnings.filterwarnings('ignore')

def eval_dataset(dataset):
    dataset = np.array(dataset)
    KErnel = RBF(length_scale_bounds = (1e-2, 1e2))
    X = dataset[:, :-1]
    Y = dataset[:, -1]
    loo = LeaveOneOut()
    y_pre_set = []
    for train_index, test_index in loo.split(X):
        X_train, X_test = X[train_index], X[test_index]
        y_train, _ = Y[train_index], Y[test_index]
        Gpr_i = GaussianProcessRegressor(kernel=KErnel,
                                        normalize_y=True,
                                        alpha = 0.1,
                                        random_state=0).fit(X_train, y_train)

        y_pre = Gpr_i.predict(X_test, return_std=True)[0]
        y_pre_set.append(y_pre)
    Rvalue = PearsonR(y_pre_set, Y)
    return Rvalue


def PearsonR(X, Y):
    X = np.array(X)
    Y = np.array(Y)
    xBar = np.mean(X)
    yBar = np.mean(Y)
    SSR = 0
    varX = 0
    varY = 0
    for i in range(0, len(X)):
        diffXXBar = X[i] - xBar
        diffYYBar = Y[i] - yBar
        SSR += (diffXXBar * diffYYBar)
        varX += diffXXBar ** 2
        varY += diffYYBar ** 2
    SST = math.sqrt(varX * varY)

    return SSR / SST

# LOF

In [4]:
import pandas as pd
import numpy as np
data = pd.read_csv('FMOdataset.csv')

In [5]:
from sklearn.neighbors import LocalOutlierFactor
model = LocalOutlierFactor(n_neighbors=4, contamination=0.03,novelty=True)   
model.fit(data.iloc[:,:-1])

y = model._predict(data.iloc[:,:-1])
y

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [6]:
index = np.where(y == -1)[0]
index

array([161])

In [7]:
for datum in range(len(index)):
    print('Outliers LOF : \n')
    print(data.iloc[index[datum],:],'\n')

Outliers LOF :

Cr                        8.6300
Si                        0.3800
Mn                        0.4200
C                         0.1000
Ni                        0.1500
Mo                        0.0013
Nb                        0.0530
W                         1.5900
V                         0.1640
P                         0.0140
Cu                        0.0000
Temperature             650.0000
Pressure                 25.0000
ExposureTime            600.0000
OxygenConcentration    8000.0000
weightgain             1584.0000
Name: 161, dtype: float64

In [8]:
data_removed = data.drop(index,axis = 0)
data_removed

,Cr,Si,Mn,C,Ni,Mo,Nb,W,V,P,Cu,Temperature,Pressure,ExposureTime,OxygenConcentration,weightgain
0,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,25.0,40,8,34.000000
1,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,25.0,580,8,43.000000
2,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,255,8,33.000000
3,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,500,8,42.000000
4,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,760,8,47.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,8.930,0.250,0.450,0.092,0.230,0.820,0.000,0.00,0.210,0.012,0.180,600,25.0,1000,10,836.000000
180,8.930,0.250,0.450,0.092,0.230,0.820,0.000,0.00,0.210,0.012,0.180,600,25.0,1500,10,993.000000
181,8.820,0.102,0.450,0.109,0.174,0.468,0.064,1.87,0.194,0.000,0.000,600,25.0,1000,25,1380.384265
182,10.830,0.270,0.640,0.110,0.390,0.300,0.054,1.89,0.190,0.009,1.020,650,20.7,500,2000,1380.010000
183,9.500,0.500,0.500,0.130,0.400,0.600,0.060,2.00,0.250,0.020,0.250,650,31.0,100,10,869.700000

In [9]:
print(eval_dataset(data))
print(eval_dataset(data_removed))

[0.77904023]
[0.77532299]

# iForest

In [10]:
from sklearn.ensemble import IsolationForest 
clf = IsolationForest( max_samples=100,random_state=0, contamination=0.03)
clf.fit(data.iloc[:,:-1])
y_pre = clf.predict(data.iloc[:,:-1])
y_pre

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [11]:
index_2 = np.where(y_pre == -1)[0]
index_2

array([ 76, 145, 146, 147, 148, 149])

In [12]:
for datum in range(len(index_2)):
    print('Outliers LOF : \n')
    print(data.iloc[index_2[datum],:],'\n')

Outliers LOF :

Cr                        8.370
Si                        0.280
Mn                        0.450
C                         0.100
Ni                        0.210
Mo                        0.900
Nb                        0.076
W                         0.000
V                         0.220
P                         0.009
Cu                        0.170
Temperature             650.000
Pressure                 20.700
ExposureTime            500.000
OxygenConcentration    2000.000
weightgain              818.000
Name: 76, dtype: float64

Outliers LOF :

Cr                       11.6
Si                        1.1
Mn                        1.8
C                         0.0
Ni                        0.0
Mo                        0.0
Nb                        0.0
W                         0.0
V                         0.0
P                         0.0
Cu                        0.0
Temperature             500.0
Pressure                 25.0
ExposureTime           1000.0
OxygenConcentration    8000.0
weightgain              570.1
Name: 145, dtype: float64

Outliers LOF :

Cr                       11.6
Si                        2.2
Mn                        1.7
C                         0.0
Ni                        0.0
Mo                        0.0
Nb                        0.0
W                         0.0
V                         0.0
P                         0.0
Cu                        0.0
Temperature             500.0
Pressure                 25.0
ExposureTime            100.0
OxygenConcentration    8000.0
weightgain              129.6
Name: 146, dtype: float64

Outliers LOF :

Cr                       11.6
Si                        2.2
Mn                        1.7
C                         0.0
Ni                        0.0
Mo                        0.0
Nb                        0.0
W                         0.0
V                         0.0
P                         0.0
Cu                        0.0
Temperature             500.0
Pressure                 25.0
ExposureTime            250.0
OxygenConcentration    8000.0
weightgain              296.4
Name: 147, dtype: float64

Outliers LOF :

Cr                       11.6
Si                        2.2
Mn                        1.7
C                         0.0
Ni                        0.0
Mo                        0.0
Nb                        0.0
W                         0.0
V                         0.0
P                         0.0
Cu                        0.0
Temperature             500.0
Pressure                 25.0
ExposureTime            500.0
OxygenConcentration    8000.0
weightgain              410.5
Name: 148, dtype: float64

Outliers LOF :

Cr                       11.6
Si                        2.2
Mn                        1.7
C                         0.0
Ni                        0.0
Mo                        0.0
Nb                        0.0
W                         0.0
V                         0.0
P                         0.0
Cu                        0.0
Temperature             500.0
Pressure                 25.0
ExposureTime           1000.0
OxygenConcentration    8000.0
weightgain              522.5
Name: 149, dtype: float64

In [13]:
data_removed_2 = data.drop(index_2,axis = 0)
data_removed_2

,Cr,Si,Mn,C,Ni,Mo,Nb,W,V,P,Cu,Temperature,Pressure,ExposureTime,OxygenConcentration,weightgain
0,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,25.0,40,8,34.000000
1,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,25.0,580,8,43.000000
2,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,255,8,33.000000
3,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,500,8,42.000000
4,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,760,8,47.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,8.930,0.250,0.450,0.092,0.230,0.820,0.000,0.00,0.210,0.012,0.180,600,25.0,1000,10,836.000000
180,8.930,0.250,0.450,0.092,0.230,0.820,0.000,0.00,0.210,0.012,0.180,600,25.0,1500,10,993.000000
181,8.820,0.102,0.450,0.109,0.174,0.468,0.064,1.87,0.194,0.000,0.000,600,25.0,1000,25,1380.384265
182,10.830,0.270,0.640,0.110,0.390,0.300,0.054,1.89,0.190,0.009,1.020,650,20.7,500,2000,1380.010000
183,9.500,0.500,0.500,0.130,0.400,0.600,0.060,2.00,0.250,0.020,0.250,650,31.0,100,10,869.700000

In [14]:
print(eval_dataset(data))
print(eval_dataset(data_removed_2))

[0.77904023]
[0.76534921]

# TCGPR

In [2]:
from TCGPR import TCGPR
dataSet = "FMOdataset.csv" 
sampling_cap = 1
# for fdata screening (backward)
# ratio is recommend as a float <= 0.01
ratio = 0.005
up_search = 150

TCGPR.fit(filePath = dataSet,Sequence = 'backward',up_search=up_search,sampling_cap = sampling_cap, ratio = ratio, alpha=0.05)

Modle Data screening of backward searching is executed : param initial_set_cap is masked
The first execution of TCGPR : Data screening; backward version
It a greedy searching strategy, since the sampling_cap is 1
1-th iteration : The newly removed datum is
[9.500e+00 5.000e-01 5.000e-01 1.300e-01 4.000e-01 6.000e-01 6.000e-02
 2.000e+00 2.500e-01 2.000e-02 2.500e-01 6.500e+02 3.100e+01 1.500e+03
 1.000e+01 1.479e+02]
****************************************************************************************************
The dataset after data screening is :
     Cr   Si   Mn     C   Ni   Mo    Nb    W     V     P    Cu  Temperature  \
0  9.5  0.5  0.5  0.13  0.4  0.6  0.06  2.0  0.25  0.02  0.25        650.0

   Pressure  ExposureTime  OxygenConcentration  weightgain
0      31.0        1500.0                 10.0       147.9
The changes of fitting goodness is :
 [0.7746323389023482, 0.8030229040168503]
The dataset after data screening has been saved successfully!
****************************************************************************************************
One conherenced dataset has been saved !
====================================================================================================

In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv('FMOdataset.csv')

In [2]:
data

,Cr,Si,Mn,C,Ni,Mo,Nb,W,V,P,Cu,Temperature,Pressure,ExposureTime,OxygenConcentration,weightgain
0,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,25.0,40,8,34.000000
1,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,25.0,580,8,43.000000
2,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,255,8,33.000000
3,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,500,8,42.000000
4,8.895,0.235,0.401,0.102,0.121,0.889,0.079,0.00,0.202,0.019,0.085,400,30.0,760,8,47.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,8.930,0.250,0.450,0.092,0.230,0.820,0.000,0.00,0.210,0.012,0.180,600,25.0,1000,10,836.000000
180,8.930,0.250,0.450,0.092,0.230,0.820,0.000,0.00,0.210,0.012,0.180,600,25.0,1500,10,993.000000
181,8.820,0.102,0.450,0.109,0.174,0.468,0.064,1.87,0.194,0.000,0.000,600,25.0,1000,25,1380.384265
182,10.830,0.270,0.640,0.110,0.390,0.300,0.054,1.89,0.190,0.009,1.020,650,20.7,500,2000,1380.010000
183,9.500,0.500,0.500,0.130,0.400,0.600,0.060,2.00,0.250,0.020,0.250,650,31.0,100,10,869.700000

In [ ]:
from TCGPR import TCGPR
dataSet = "FMOdataset.csv" 
sampling_cap = 1
# for fdata screening (backward)
# ratio is recommend as a float <= 0.01
ratio = 0.005
up_search = 150

TCGPR.fit(filePath = dataSet, Mission='FEATURE',initial_set_cap=[2,3,8],up_search=up_search,sampling_cap = sampling_cap, ratio = ratio, alpha=0.05)

.. [TCGPR]: A Machine Learning Algorithms for Screening Abnormal Data and Important features of Small DataSet
.. [Info]: V1.2, Bin Cao (bcao@shu.edu.cn), MGI, SHU, Shanghai, CHINA.
References :
----------
.. [1] https://github.com/Bin-Cao/TCGPR/blob/main/Intro/TCGPR.pdf
.. [2] Software copyright 2022SR1423038 (2022): Zhang Tong-yi, Cao Bin, Sun Sheng.
.. [3] Patent CN 115017977 A(2022): Zhang Tong-yi, Cao Bin, Yuan Hao, Wei Qinghua, Dong Ziqiang.
============================================================
The first execution of TCGPR : Feature selection
THE specific Initial feature set is
       Mn      C      V
0  0.401  0.102  0.202
1  0.401  0.102  0.202
2  0.401  0.102  0.202
3  0.401  0.102  0.202
4  0.401  0.102  0.202
----------------------------------------------------------------------------------------------------
It a greedy searching strategy, since the sampling_cap is 1